---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - objectstorage.k8s.io_bucketaccesses.yaml
  - objectstorage.k8s.io_bucketaccessclasses.yaml
  - objectstorage.k8s.io_bucketaccessrequests.yaml
  - objectstorage.k8s.io_bucketclasses.yaml
  - objectstorage.k8s.io_bucketrequests.yaml
  - objectstorage.k8s.io_buckets.yaml
